const loader=document.getElementById('loader');window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),550));
const progress=document.getElementById('progress');window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(scrollY/h*100)+'%'});
const nav=document.getElementById('nav');let last=0;window.addEventListener('scroll',()=>{if(scrollY>last&&scrollY>130)nav.classList.add('hide');else nav.classList.remove('hide');last=scrollY});
const hamb=document.getElementById('hamb'),menu=document.getElementById('mobileMenu');hamb.onclick=()=>menu.classList.toggle('open');menu.querySelectorAll('a').forEach(a=>a.onclick=()=>menu.classList.remove('open'));
const cursor=document.getElementById('cursor'),dot=document.getElementById('cursorDot');window.addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px'});
document.querySelectorAll('a,button,.service-card').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.style.transform='translate(-50%,-50%) scale(1.65)');el.addEventListener('mouseleave',()=>cursor.style.transform='translate(-50%,-50%) scale(1)')});
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');if(e.target.querySelectorAll('[data-count]').length)runCounters(e.target)}}),{threshold:.18});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
let counted=false;function runCounters(scope){if(counted)return;counted=true;scope.querySelectorAll('[data-count]').forEach(el=>{const end=+el.dataset.count;let n=0;const step=Math.max(1,Math.ceil(end/55));const t=setInterval(()=>{n+=step;if(n>=end){n=end;clearInterval(t)}el.textContent=end===100?'%'+n:n},24)})}
document.querySelectorAll('.faq-q').forEach(q=>q.addEventListener('click',()=>{const a=q.nextElementSibling;a.classList.toggle('open');q.querySelector('span').textContent=a.classList.contains('open')?'−':'+'}));
document.querySelectorAll('.magnetic').forEach(btn=>{btn.addEventListener('mousemove',e=>{const r=btn.getBoundingClientRect();btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.16}px,${(e.clientY-r.top-r.height/2)*.16}px)`});btn.addEventListener('mouseleave',()=>btn.style.transform='translate(0,0)')});
const canvas=document.getElementById('sparkCanvas'),ctx=canvas.getContext('2d');let w,h,parts=[];function resize(){w=canvas.width=innerWidth;h=canvas.height=innerHeight;const count=innerWidth<700?38:95;parts=Array.from({length:count},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*2+0.7,vx:(Math.random()-.5)*.22,vy:Math.random()*.45+.12,a:Math.random()*.7+.2}))}resize();addEventListener('resize',resize);function draw(){ctx.clearRect(0,0,w,h);for(const p of parts){p.x+=p.vx;p.y+=p.vy;if(p.y>h+10){p.y=-10;p.x=Math.random()*w}if(p.x<0)p.x=w;if(p.x>w)p.x=0;const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,p.r*7);g.addColorStop(0,`rgba(255,215,155,${p.a})`);g.addColorStop(1,'rgba(255,95,174,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,p.r*7,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}draw();
const heroImg=document.querySelector('.hero-bg img');window.addEventListener('mousemove',e=>{if(innerWidth<800)return;const x=(e.clientX/innerWidth-.5)*18;const y=(e.clientY/innerHeight-.5)*18;heroImg.style.transform=`scale(1.07) translate(${x}px,${y}px)`});
